version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../public_html:/var/www
  nginx:
    build:
      context: ./nginx
    volumes:
      - ../public_html:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
    depends_on:
      - php-fpm
    ports:
      - "8090:80"
      - "4439:443"
  